version: '3'

services:
  api:
    build: ./weather-data-server
    restart: unless-stopped
    ports:
    - "8080:8080"
    links:
    - "db:db"

  web:
    build: ./weather-data-webapp
    restart: unless-stopped
    

  db:
    image: neo4j:latest
    restart: unless-stopped
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
    - neo4j/data:/data
 
  proxy:
    build: ./proxy
    links:
    - web
    - api
    ports:
      - "80:80"
      
    restart: unless-stopped
